spring:
  application:
    name: event-config-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:eventconfig}
      username: ${MONGODB_USERNAME:root}
      password: ${MONGODB_PASSWORD:root}
      authentication-database: ${MONGODB_AUTH_DATABASE:admin}

  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://localhost:9200}
    username: ${ELASTICSEARCH_USERNAME:}
    password: ${ELASTICSEARCH_PASSWORD:}

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

app:
  storage:
    type: ${STORAGE_TYPE:mongodb}

logging:
  level:
    root: INFO
    com.flex.mind.tech: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html